#pragma once

#include "shahbaz/command/command_dispatcher.hpp"
#include "shahbaz/interfaces/byte_view.hpp"
#include "shahbaz/interfaces/monotonic_clock.hpp"
#include "shahbaz/link/device_frame_sender.hpp"
#include "shahbaz/link/sensor_telemetry_publisher.hpp"
#include "shahbaz/protocol/frame_accumulator.hpp"
#include "shahbaz/safety/actuator_controller.hpp"
#include "shahbaz/safety/safety_supervisor.hpp"
#include "shahbaz/sensors/sensor_scheduler.hpp"

#include <cstddef>
#include <cstdint>

namespace shahbaz::link {

struct ProtocolEngineStatistics final {
    std::uint32_t bytes_received{};
    std::uint32_t frames_received{};
    std::uint32_t frames_rejected{};
    std::uint32_t session_rejects{};
    std::uint32_t freshness_rejects{};
    std::uint32_t replies_sent{};
    std::uint32_t reply_drops{};
};

/** Runtime facts reported by DeviceInfoResponse rather than hard-coded claims. */
struct DeviceRuntimeInfo final {
    std::uint32_t detected_flash_bytes{};
    std::uint32_t detected_psram_bytes{};
    std::uint32_t board_issue_mask{};
    std::uint8_t supported_motor_channels{4U};
    std::uint8_t supported_servo_channels{2U};
    std::uint8_t active_motor_channels{};
    std::uint8_t active_servo_channels{};
    bool actuator_available{};
    bool actuators_enabled_by_config{};
};

struct ProtocolEngineConfig final {
    /** Maximum sender age after mapping the host monotonic clock into device time. */
    std::uint64_t maximum_sender_age_us{250'000U};
    /** Small scheduling/clock-estimation tolerance for frames apparently in the future. */
    std::uint64_t maximum_sender_future_skew_us{50'000U};
};

class ProtocolEngine final {
  public:
    ProtocolEngine(command::CommandDispatcher& dispatcher,
                   safety::SafetySupervisor& safety,
                   safety::IActuatorController& actuator,
                   sensors::scheduler::SharedSensorScheduler& sensors,
                   SensorTelemetryPublisher& telemetry,
                   DeviceFrameSender& sender,
                   interfaces::IMonotonicClock& clock,
                   DeviceRuntimeInfo runtime_info = {},
                   ProtocolEngineConfig config = {}) noexcept;

    /**
     * Starts or ends a logical CDC session. A connected session requires a
     * fresh non-zero hardware-RNG token generated by the platform layer.
     */
    void setConnected(bool connected, std::uint64_t session_token = 0U) noexcept;
    void consume(interfaces::ConstByteView bytes) noexcept;
    [[nodiscard]] auto statistics() const noexcept -> const ProtocolEngineStatistics& {
        return statistics_;
    }
    [[nodiscard]] auto timeSynchronized() const noexcept -> bool { return time_synchronized_; }
    [[nodiscard]] auto sessionToken() const noexcept -> std::uint64_t { return session_token_; }

  private:
    [[nodiscard]] auto senderFreshness(const protocol::DecodedFrame& frame,
                                       std::uint64_t received_us) const noexcept
        -> command::SenderFreshness;
    [[nodiscard]] auto validateAndStripSessionToken(const protocol::DecodedFrame& input,
                                                    protocol::DecodedFrame& output) noexcept
        -> bool;
    void establishTimeMapping(const protocol::DecodedFrame& frame,
                              std::uint64_t received_us) noexcept;
    void processFrame(const protocol::DecodedFrame& frame,
                      std::uint64_t received_us) noexcept;
    [[nodiscard]] auto applyAction(const command::DispatchResult& result,
                                   const protocol::DecodedFrame& request,
                                   std::uint64_t now_us) noexcept -> bool;
    void sendReply(const command::DispatchResult& result,
                   const protocol::DecodedFrame& request,
                   std::uint64_t received_us,
                   std::uint64_t now_us) noexcept;
    void sendNack(std::uint32_t request_sequence,
                  protocol::NackReason reason,
                  command::ValidationError validation) noexcept;
    void countReply(interfaces::TransportStatus status) noexcept;
    static void increment(std::uint32_t& value) noexcept;
    [[nodiscard]] static auto sessionBound(protocol::MessageType type) noexcept -> bool;

    command::CommandDispatcher& dispatcher_;
    safety::SafetySupervisor& safety_;
    safety::IActuatorController& actuator_;
    sensors::scheduler::SharedSensorScheduler& sensors_;
    SensorTelemetryPublisher& telemetry_;
    DeviceFrameSender& sender_;
    interfaces::IMonotonicClock& clock_;
    DeviceRuntimeInfo runtime_info_{};
    ProtocolEngineConfig config_{};
    protocol::FrameAccumulator accumulator_{};
    ProtocolEngineStatistics statistics_{};
    std::uint64_t session_token_{};
    std::uint64_t sync_sender_us_{};
    std::uint64_t sync_device_rx_us_{};
    bool connected_{false};
    bool time_synchronized_{false};
};

}  // namespace shahbaz::link
